// Operix page-level translations.
// This handles rewritten pages with data-p attributes.
// It does not replace main.js; main.js still translates global nav/footer.

const OPX_PAGE_COPY = {
  en: {
    home_kicker:'AI Automation Agency',
    home_h1:'AI systems that remove busywork from your business.',
    home_sub:'Operix builds practical chatbots, workflow automations, lead systems, dashboards, and AI agents for real business operations — fast, clean, and measurable.',
    home_cta1:'Get Free Audit',
    home_cta2:'Explore Services',
    home_proof1:'Chatbots',
    home_proof2:'Lead routing',
    home_proof3:'CRM workflows',
    home_proof4:'Reports',
    home_proof5:'Content systems',
    home_services_label:'What we build',
    home_services_title:'Automation that works behind the scenes.',
    home_services_sub:'Start with one workflow or build a full AI operations layer.',
    home_s1_t:'AI Customer Support',
    home_s1_d:'Bots that answer common questions, qualify requests, and route complex cases to your team.',
    home_s2_t:'Workflow Automation',
    home_s2_d:'Replace repetitive admin work with reliable automations across your tools.',
    home_s3_t:'AI Lead Generation',
    home_s3_d:'Capture, qualify, and follow up with leads faster — without adding headcount.',
    home_s4_t:'AI Analytics',
    home_s4_d:'Turn scattered data into clear daily reports and alerts.',
    home_s5_t:'AI Content Machine',
    home_s5_d:'Draft posts, emails, product descriptions, and content ideas in your brand voice.',
    home_s6_t:'Custom AI Agents',
    home_s6_d:'Digital assistants that perform multi-step tasks inside your existing stack.',
    home_process_label:'Process',
    home_process_title:'Simple build process. No bloated consulting.',
    home_p1_t:'Audit',
    home_p1_d:'We map your workflow and find the highest-ROI automation opportunity.',
    home_p2_t:'Prototype',
    home_p2_d:'You see a working version quickly, not a 40-page document.',
    home_p3_t:'Deploy',
    home_p3_d:'We connect the system to your real tools and test the full flow.',
    home_p4_t:'Improve',
    home_p4_d:'We monitor, refine, and expand when the workflow proves useful.',
    home_outcomes_label:'Example outcomes',
    home_outcomes_title:'What automation can realistically do.',
    home_o1_t:'Lead intake',
    home_o1_d:'Respond instantly, ask qualifying questions, send hot leads to your team.',
    home_o2_t:'Support',
    home_o2_d:'Handle FAQs, status requests, returns, and routing automatically.',
    home_o3_t:'Operations',
    home_o3_d:'Move data between forms, spreadsheets, CRM, email, and dashboards.',
    home_ind_label:'Industries',
    home_ind_title:'Useful across many business types.',
    home_ind_sub:'Real estate, e-commerce, clinics, agencies, hospitality, education, logistics, retail, and more.',
    home_final_title:'Ready to find your first automation opportunity?',
    home_final_sub:'Send us your current workflow. We will tell you what should be automated first and what should stay manual.',

    services_kicker:'Services',
    services_h1:'Everything you need to automate your business.',
    services_sub:'From a single chatbot to a full AI operations system — we build, deploy, and maintain practical automation.',
    svc1_t:'AI Customer Support',
    svc1_d:'A bot that answers customer questions, qualifies requests, books calls, and escalates complex cases to your team.',
    svc1_f1:'Website, Telegram, WhatsApp, or email intake',
    svc1_f2:'Multi-language customer flows',
    svc1_f3:'Human handoff for complex cases',
    svc1_f4:'Conversation logs and reporting',
    svc2_t:'Workflow Automation',
    svc2_d:'We connect the tools you already use and remove repetitive steps from your daily operations.',
    svc2_f1:'Form-to-CRM automation',
    svc2_f2:'Invoice, email, and task workflows',
    svc2_f3:'Alerts, reminders, and status updates',
    svc2_f4:'Error handling and fallback logic',
    svc3_t:'AI Lead Generation',
    svc3_d:'Systems that capture leads, qualify them, personalize follow-ups, and notify your sales team when prospects are ready.',
    svc3_f1:'Lead capture and scoring',
    svc3_f2:'Personalized follow-up sequences',
    svc3_f3:'CRM enrichment',
    svc3_f4:'Sales-ready lead notifications',
    svc4_t:'AI Analytics',
    svc4_d:'Dashboards and AI summaries that turn your scattered data into decisions you can act on.',
    svc4_f1:'Daily or weekly reports',
    svc4_f2:'Plain-English AI summaries',
    svc4_f3:'Anomaly and KPI alerts',
    svc4_f4:'Spreadsheet, CRM, and platform integrations',
    svc5_t:'AI Content Machine',
    svc5_d:'A repeatable content workflow for posts, emails, product descriptions, and campaign drafts.',
    svc5_f1:'Brand voice setup',
    svc5_f2:'Content calendar support',
    svc5_f3:'Draft generation and review flow',
    svc5_f4:'Publishing-ready assets',
    svc6_t:'Custom AI Agents',
    svc6_d:'For complex workflows that need an AI assistant to reason, plan, and execute multi-step tasks.',
    svc6_f1:'Custom logic and tool access',
    svc6_f2:'API and database integrations',
    svc6_f3:'Action logs and approval steps',
    svc6_f4:'Designed around your exact workflow',

    pricing_kicker:'Pricing',
    pricing_h1:'Transparent pricing. No surprises.',
    pricing_sub:'Start small, prove value, then expand. Every project is scoped before payment so you know what you are buying.',
    plan1_name:'Starter',
    plan1_price:'$300',
    plan1_suffix:'/project',
    plan1_desc:'Best for one focused chatbot or automation workflow.',
    plan1_f1:'1 AI chatbot or automation workflow',
    plan1_f2:'Setup and deployment included',
    plan1_f3:'Telegram or web widget integration',
    plan1_f4:'2 weeks post-launch support',
    plan1_f5:'Basic performance report',
    plan2_name:'Growth',
    plan2_tag:'Most useful',
    plan2_price:'$700',
    plan2_suffix:'/project',
    plan2_desc:'Best for a complete automation system with multiple connected pieces.',
    plan2_f1:'Up to 3 automations or chatbots',
    plan2_f2:'CRM and tool integration',
    plan2_f3:'Lead qualification system',
    plan2_f4:'Monthly optimization review',
    plan2_f5:'Priority support',
    plan2_f6:'Analytics dashboard',
    plan3_name:'Custom',
    plan3_price:'Custom',
    plan3_suffix:'',
    plan3_desc:'For deeper integrations, custom AI agents, or multi-department systems.',
    plan3_f1:'Custom AI agent development',
    plan3_f2:'Full-stack integrations',
    plan3_f3:'Dedicated project plan',
    plan3_f4:'Advanced testing and documentation',
    plan3_f5:'Ongoing support options',
    pricing_btn_start:'Get started',
    pricing_btn_contact:'Contact us',
    retainer_kicker:'Retainers',
    retainer_h:'Keep your system sharp.',
    retainer_sub:'Optional monthly support after launch.',
    retainer1_t:'Maintenance',
    retainer1_p:'Bug fixes, uptime checks, and minor updates.',
    retainer2_t:'Growth',
    retainer2_p:'Maintenance plus optimization, testing, and small feature additions.',
    retainer3_t:'Scale',
    retainer3_p:'Managed improvement backlog, strategy calls, and priority support.',
    compare_kicker:'Compare',
    compare_h:'What is included.',
    faq_kicker:'FAQ',
    faq_h:'Clear answers.',
    faq1_q:'Are there hidden fees?',
    faq1_a:'No. We scope the project before payment. Third-party API costs, if any, are estimated upfront.',
    faq2_q:'Do I pay upfront?',
    faq2_a:'Usually 50% upfront and 50% after delivery. Larger projects can use milestones.',
    faq3_q:'What if I need something between plans?',
    faq3_a:'We can scope a custom project. The plans are starting points, not hard limits.',
    faq4_q:'What happens after launch?',
    faq4_a:'You can run the system yourself or add a monthly retainer for support and optimization.',

    cases_kicker:'Demo workflows',
    cases_h1:'Automation scenarios, shown honestly.',
    cases_sub:'These are example workflows we can build. Real client case studies should only be published with client permission.',
    cases_note:'No fake client claims: the cards below are demo automation scenarios, not proof that a specific company hired Operix.',
    case1_t:'Lead qualification bot for real estate',
    case1_d:'A website or Telegram bot asks buyer questions, captures budget/location, and sends qualified leads to the agent.',
    case1_m1:'Instant',
    case1_l1:'Lead response',
    case1_m2:'CRM',
    case1_l2:'Auto-fill',
    case1_m3:'24/7',
    case1_l3:'Availability',
    case2_t:'Customer support automation for online stores',
    case2_d:'AI answers order status, returns, sizing, shipping, and common product questions before handing off complex cases.',
    case2_m1:'FAQ',
    case2_l1:'Automated',
    case2_m2:'Tickets',
    case2_l2:'Sorted',
    case2_m3:'Team',
    case2_l3:'Less routine',
    case3_t:'Content pipeline for service businesses',
    case3_d:'A structured system generates drafts for posts, email newsletters, landing pages, and product descriptions.',
    case3_m1:'Drafts',
    case3_l1:'Generated',
    case3_m2:'Tone',
    case3_l2:'Consistent',
    case3_m3:'Calendar',
    case3_l3:'Planned',
    case4_t:'Client intake automation for law or consulting',
    case4_d:'Forms collect details, classify requests, summarize key facts, and prepare the next step for the team.',
    case4_m1:'Forms',
    case4_l1:'Structured',
    case4_m2:'Docs',
    case4_l2:'Summarized',
    case4_m3:'Next step',
    case4_l3:'Suggested',
    case5_t:'Guest support bot for hospitality',
    case5_d:'A multilingual assistant answers booking questions, policies, check-in details, and routes urgent requests.',
    case5_m1:'Guests',
    case5_l1:'Answered',
    case5_m2:'Languages',
    case5_l2:'Supported',
    case5_m3:'Requests',
    case5_l3:'Routed',
    case6_t:'Candidate screening for recruitment',
    case6_d:'AI reviews applications against criteria, tags candidates, summarizes CVs, and helps schedule interviews.',
    case6_m1:'CVs',
    case6_l1:'Screened',
    case6_m2:'Scores',
    case6_l2:'Assigned',
    case6_m3:'Interviews',
    case6_l3:'Scheduled',
    cases_cta:'Discuss this workflow',

    about_kicker:'About Operix',
    about_h1:'A focused AI automation studio.',
    about_sub:'Operix builds practical AI systems for small and mid-size businesses that need results, not hype.',
    about_mission_k:'Mission',
    about_mission_h:'AI automation should be accessible, useful, and honest.',
    about_mission_p1:'We help businesses remove repetitive work, respond faster, and build cleaner operations with AI.',
    about_mission_p2:'We prefer small, measurable systems over bloated consulting. First we prove value, then we scale what works.',
    about_stat1:'Prototype-first',
    about_stat1_d:'You see a working system early.',
    about_stat2:'EN/RU',
    about_stat2_d:'Communication and systems can support both languages.',
    about_stat3:'Remote',
    about_stat3_d:'Built for global, online-first teams.',
    about_why_k:'Principles',
    about_why_h:'How we operate.',
    about_v1_h:'Clarity',
    about_v1_p:'You know what we are building, why it matters, and what it costs.',
    about_v2_h:'Speed',
    about_v2_p:'We move fast, but we do not pretend unfinished systems are complete.',
    about_v3_h:'Honesty',
    about_v3_p:'No fake case studies, no inflated claims, no confusing technical talk.',
    about_v4_h:'Systems thinking',
    about_v4_p:'We do not just add AI. We redesign the workflow around useful automation.',
    about_v5_h:'Iteration',
    about_v5_p:'Good automation improves after real users touch it.',
    about_v6_h:'Ownership',
    about_v6_p:'We document the system so your team can understand and use it.',

    blog_kicker:'Playbooks',
    blog_h1:'AI automation notes and guides.',
    blog_sub:'No fake blog links. These are planned playbooks and topics we can turn into full articles.',
    blog_note:'The blog is intentionally marked as coming soon until each article is actually published.',
    blog1_t:'How to automate customer support in 5 days',
    blog1_p:'A practical outline for mapping FAQs, choosing channels, testing responses, and adding human handoff.',
    blog2_t:'The real ROI of AI automation for small businesses',
    blog2_p:'How to measure time saved, response speed, cost reduction, and conversion improvements without fake numbers.',
    blog3_t:'AI workflows for real estate agencies',
    blog3_p:'Lead qualification, appointment scheduling, CRM updates, and follow-up sequences.',
    blog4_t:'Telegram vs WhatsApp for business bots',
    blog4_p:'Which channel fits your audience, budget, compliance, and daily workflow.',
    blog5_t:'E-commerce automations to build first',
    blog5_p:'Order status, returns, abandoned carts, review requests, and product descriptions.',
    blog6_t:'How to launch a multilingual support bot',
    blog6_p:'Language detection, fallback messages, escalation, and testing across regions.',
    blog_status:'Coming soon',

    contact_kicker:'Contact',
    contact_h1:'Tell us what you want to automate.',
    contact_sub:'Send your workflow, tools, and goal. We will reply with the clearest first automation opportunity.',
    contact_left_h:'Free audit',
    contact_left_p:'No pressure, no fake strategy call. We look at your process and tell you what is worth automating first.',
    contact_b1:'Workflow review',
    contact_b2:'Automation idea',
    contact_b3:'Suggested tools',
    contact_b4:'Rough budget',
    contact_b5:'Next step',
    contact_form_h:'Project request',
    contact_form_p:'The form is delivered through Formspree to our email.',
    contact_name:'Name',
    contact_email:'Email',
    contact_company:'Company',
    contact_budget:'Budget',
    contact_service:'Service',
    contact_message:'Message',
    contact_send:'Send message',
    contact_privacy:'Your message may be processed by Formspree to deliver it to Operix. We do not sell your data.',
    contact_success_h:'Message sent.',
    contact_success_p:'Thanks. We will review your workflow and reply as soon as possible.',
    contact_error:'Failed. Email us: travisofwork@gmail.com',

    privacy_kicker:'Legal',
    privacy_h1:'Privacy Policy',
    privacy_sub:'Last updated: June 2026',
    privacy_intro:'Operix respects your privacy. This policy explains what information we collect and how we use it.',
    privacy_h2_1:'Information we collect',
    privacy_l1:'Contact details you submit through the contact form, such as name, email, company, budget, selected service, and message.',
    privacy_l2:'Messages you send to us through Telegram or email.',
    privacy_l3:'Basic website usage data if analytics are enabled.',
    privacy_h2_2:'How we use information',
    privacy_l4:'To reply to your inquiry and provide requested services.',
    privacy_l5:'To prepare project proposals, scope automation work, and communicate about delivery.',
    privacy_l6:'To improve our website and services.',
    privacy_l7:'We do not sell your personal data.',
    privacy_h2_3:'Formspree',
    privacy_p3:'Our contact form uses Formspree to route submissions to our email. This means your form data may be processed by Formspree as a third-party service provider.',
    privacy_h2_4:'Data retention',
    privacy_p4:'We keep communication records only as long as necessary for business, legal, and service delivery purposes.',
    privacy_h2_5:'Your rights',
    privacy_p5:'You can ask us to access, correct, or delete your personal information by emailing travisofwork@gmail.com.',
    privacy_h2_6:'Contact',
    privacy_p6:'Questions about privacy? Email travisofwork@gmail.com or message Telegram @exyysdof.',

    terms_kicker:'Legal',
    terms_h1:'Terms of Service',
    terms_sub:'Last updated: June 2026',
    terms_intro:'By working with Operix, you agree to these terms. Project-specific details are defined in the written proposal or agreement.',
    terms_h2_1:'Services',
    terms_p1:'Operix provides AI automation development, workflow design, chatbot setup, integrations, and consulting.',
    terms_h2_2:'Scope',
    terms_p2:'Every project should have a defined scope, deliverables, timeline, and price before work begins.',
    terms_h2_3:'Payment',
    terms_l1:'Projects are usually paid 50% upfront and 50% on delivery unless otherwise agreed.',
    terms_l2:'Retainers are billed monthly in advance.',
    terms_l3:'Third-party costs such as APIs, hosting, or automation platforms are separate unless included in the proposal.',
    terms_h2_4:'Delivery',
    terms_p4:'Delivery timelines are estimates. Delays caused by missing client feedback, unavailable third-party tools, or scope changes may change the timeline.',
    terms_h2_5:'Revisions',
    terms_p5:'Projects include reasonable revisions within the agreed scope. New features or scope changes may require additional payment.',
    terms_h2_6:'Refunds',
    terms_p6:'If Operix fails to deliver the agreed scope, we will discuss correction or refund options. Refunds are not issued for change-of-mind after work has started.',
    terms_h2_7:'Liability',
    terms_p7:'Operix is not responsible for indirect losses. Our total liability is limited to the amount paid for the specific project.',
    terms_h2_8:'Contact',
    terms_p8:'Questions? Email travisofwork@gmail.com or Telegram @exyysdof.'
  },
  ru: {}
};

// Russian copy
OPX_PAGE_COPY.ru = {
  home_kicker:'AI Automation Agency',
  home_h1:'AI-системы, которые убирают рутину из бизнеса.',
  home_sub:'Operix создаёт практичные чатботы, автоматизации процессов, lead-системы, дашборды и AI-агентов для реальных бизнес-операций — быстро, аккуратно и измеримо.',
  home_cta1:'Получить бесплатный аудит',
  home_cta2:'Смотреть услуги',
  home_proof1:'Чатботы',
  home_proof2:'Маршрутизация лидов',
  home_proof3:'CRM-процессы',
  home_proof4:'Отчёты',
  home_proof5:'Контент-системы',
  home_services_label:'Что мы строим',
  home_services_title:'Автоматизация, которая работает в фоне.',
  home_services_sub:'Можно начать с одного процесса или построить полноценный AI-слой для операций.',
  home_s1_t:'AI поддержка клиентов',
  home_s1_d:'Боты отвечают на частые вопросы, квалифицируют запросы и передают сложные случаи команде.',
  home_s2_t:'Автоматизация процессов',
  home_s2_d:'Заменяем повторяющуюся ручную работу надёжными автоматизациями между вашими инструментами.',
  home_s3_t:'AI генерация лидов',
  home_s3_d:'Быстрее собирайте, квалифицируйте и догревайте лиды без найма новых сотрудников.',
  home_s4_t:'AI аналитика',
  home_s4_d:'Превращаем разрозненные данные в понятные ежедневные отчёты и уведомления.',
  home_s5_t:'AI контент-машина',
  home_s5_d:'Черновики постов, писем, описаний товаров и идей в голосе вашего бренда.',
  home_s6_t:'Кастомные AI агенты',
  home_s6_d:'Цифровые ассистенты, которые выполняют многошаговые задачи внутри вашего стека.',
  home_process_label:'Процесс',
  home_process_title:'Простой процесс разработки. Без раздутого консалтинга.',
  home_p1_t:'Аудит',
  home_p1_d:'Разбираем ваш процесс и находим самую полезную точку для автоматизации.',
  home_p2_t:'Прототип',
  home_p2_d:'Вы быстро видите рабочую версию, а не документ на 40 страниц.',
  home_p3_t:'Запуск',
  home_p3_d:'Подключаем систему к реальным инструментам и тестируем весь путь.',
  home_p4_t:'Улучшение',
  home_p4_d:'Отслеживаем, дорабатываем и расширяем, когда процесс показывает пользу.',
  home_outcomes_label:'Примеры результатов',
  home_outcomes_title:'Что автоматизация реально может сделать.',
  home_o1_t:'Приём лидов',
  home_o1_d:'Мгновенный ответ, уточняющие вопросы и передача горячих лидов команде.',
  home_o2_t:'Поддержка',
  home_o2_d:'FAQ, статус заказов, возвраты и маршрутизация запросов автоматически.',
  home_o3_t:'Операции',
  home_o3_d:'Передача данных между формами, таблицами, CRM, email и дашбордами.',
  home_ind_label:'Индустрии',
  home_ind_title:'Полезно для разных типов бизнеса.',
  home_ind_sub:'Недвижимость, e-commerce, клиники, агентства, hospitality, образование, логистика, ритейл и другое.',
  home_final_title:'Готовы найти первую точку автоматизации?',
  home_final_sub:'Отправьте текущий процесс. Мы скажем, что автоматизировать первым, а что лучше оставить ручным.',

  services_kicker:'Услуги',
  services_h1:'Всё, что нужно для автоматизации бизнеса.',
  services_sub:'От одного чатбота до полноценной AI-операционной системы — строим, запускаем и поддерживаем практичные автоматизации.',
  svc1_t:'AI поддержка клиентов',
  svc1_d:'Бот отвечает на вопросы, квалифицирует запросы, записывает на звонки и передаёт сложные случаи команде.',
  svc1_f1:'Сайт, Telegram, WhatsApp или email-входящие',
  svc1_f2:'Мультиязычные сценарии',
  svc1_f3:'Передача живому менеджеру',
  svc1_f4:'Логи диалогов и отчётность',
  svc2_t:'Автоматизация процессов',
  svc2_d:'Соединяем ваши текущие инструменты и убираем повторяющиеся шаги из ежедневной работы.',
  svc2_f1:'Автоматизация form-to-CRM',
  svc2_f2:'Счета, email и задачи',
  svc2_f3:'Уведомления, напоминания и статусы',
  svc2_f4:'Обработка ошибок и fallback-логика',
  svc3_t:'AI генерация лидов',
  svc3_d:'Системы собирают лиды, квалифицируют, персонализируют follow-up и уведомляют продажников о готовых клиентах.',
  svc3_f1:'Сбор и scoring лидов',
  svc3_f2:'Персонализированные follow-up цепочки',
  svc3_f3:'Обогащение CRM',
  svc3_f4:'Уведомления о готовых лидах',
  svc4_t:'AI аналитика',
  svc4_d:'Дашборды и AI-сводки, которые превращают разрозненные данные в понятные решения.',
  svc4_f1:'Ежедневные или еженедельные отчёты',
  svc4_f2:'AI-сводки простым языком',
  svc4_f3:'Уведомления по KPI и аномалиям',
  svc4_f4:'Интеграции с таблицами, CRM и платформами',
  svc5_t:'AI контент-машина',
  svc5_d:'Повторяемый контент-процесс для постов, email, описаний товаров и черновиков кампаний.',
  svc5_f1:'Настройка голоса бренда',
  svc5_f2:'Поддержка контент-календаря',
  svc5_f3:'Генерация и review-процесс',
  svc5_f4:'Материалы, готовые к публикации',
  svc6_t:'Кастомные AI агенты',
  svc6_d:'Для сложных процессов, где AI должен рассуждать, планировать и выполнять многошаговые задачи.',
  svc6_f1:'Кастомная логика и доступ к инструментам',
  svc6_f2:'API и database-интеграции',
  svc6_f3:'Логи действий и approval steps',
  svc6_f4:'Под ваш конкретный workflow',

  pricing_kicker:'Цены',
  pricing_h1:'Прозрачные цены. Без сюрпризов.',
  pricing_sub:'Начинаем с малого, доказываем пользу, затем расширяем. Каждый проект согласуется до оплаты.',
  plan1_name:'Starter',
  plan1_price:'$300',
  plan1_suffix:'/проект',
  plan1_desc:'Для одного сфокусированного чатбота или workflow.',
  plan1_f1:'1 AI чатбот или автоматизация',
  plan1_f2:'Настройка и запуск включены',
  plan1_f3:'Telegram или web widget',
  plan1_f4:'2 недели поддержки после запуска',
  plan1_f5:'Базовый отчёт по работе',
  plan2_name:'Growth',
  plan2_tag:'Самый полезный',
  plan2_price:'$700',
  plan2_suffix:'/проект',
  plan2_desc:'Для полноценной системы с несколькими связанными частями.',
  plan2_f1:'До 3 автоматизаций или чатботов',
  plan2_f2:'Интеграция с CRM и инструментами',
  plan2_f3:'Система квалификации лидов',
  plan2_f4:'Ежемесячный review оптимизации',
  plan2_f5:'Приоритетная поддержка',
  plan2_f6:'Дашборд аналитики',
  plan3_name:'Custom',
  plan3_price:'Custom',
  plan3_suffix:'',
  plan3_desc:'Для глубоких интеграций, кастомных AI-агентов или систем на несколько отделов.',
  plan3_f1:'Разработка кастомного AI-агента',
  plan3_f2:'Глубокие интеграции',
  plan3_f3:'Отдельный project plan',
  plan3_f4:'Расширенное тестирование и документация',
  plan3_f5:'Варианты ongoing support',
  pricing_btn_start:'Начать',
  pricing_btn_contact:'Связаться',
  retainer_kicker:'Ретейнеры',
  retainer_h:'Поддерживаем систему в форме.',
  retainer_sub:'Опциональная ежемесячная поддержка после запуска.',
  retainer1_t:'Maintenance',
  retainer1_p:'Bug fixes, uptime checks и небольшие обновления.',
  retainer2_t:'Growth',
  retainer2_p:'Maintenance плюс оптимизация, тесты и небольшие фичи.',
  retainer3_t:'Scale',
  retainer3_p:'Managed backlog улучшений, strategy calls и priority support.',
  compare_kicker:'Сравнение',
  compare_h:'Что входит.',
  faq_kicker:'FAQ',
  faq_h:'Чёткие ответы.',
  faq1_q:'Есть скрытые платежи?',
  faq1_a:'Нет. Мы согласуем scope до оплаты. Сторонние API-расходы, если есть, оцениваются заранее.',
  faq2_q:'Нужно платить заранее?',
  faq2_a:'Обычно 50% upfront и 50% после delivery. Большие проекты можно разбить на milestones.',
  faq3_q:'А если нужно что-то между тарифами?',
  faq3_a:'Можем собрать кастомный scope. Тарифы — стартовые точки, не жёсткие рамки.',
  faq4_q:'Что после запуска?',
  faq4_a:'Можно вести систему самостоятельно или подключить monthly retainer для поддержки и оптимизации.',

  cases_kicker:'Demo workflows',
  cases_h1:'Сценарии автоматизации, честно показанные.',
  cases_sub:'Это примеры workflows, которые мы можем построить. Реальные кейсы клиентов стоит публиковать только с разрешения клиента.',
  cases_note:'Без фейковых client claims: карточки ниже — demo-сценарии автоматизации, а не доказательство, что конкретная компания нанимала Operix.',
  case1_t:'Бот квалификации лидов для недвижимости',
  case1_d:'Бот на сайте или в Telegram задаёт вопросы покупателю, собирает бюджет/локацию и передаёт qualified leads агенту.',
  case1_m1:'Instant',
  case1_l1:'Ответ лиду',
  case1_m2:'CRM',
  case1_l2:'Auto-fill',
  case1_m3:'24/7',
  case1_l3:'Доступность',
  case2_t:'Автоматизация поддержки для online stores',
  case2_d:'AI отвечает по статусу заказа, возвратам, размерам, доставке и частым вопросам, сложные случаи передаёт команде.',
  case2_m1:'FAQ',
  case2_l1:'Автоматизировано',
  case2_m2:'Tickets',
  case2_l2:'Отсортированы',
  case2_m3:'Team',
  case2_l3:'Меньше рутины',
  case3_t:'Контент-пайплайн для сервисных бизнесов',
  case3_d:'Система генерирует черновики постов, email-рассылок, лендингов и описаний продуктов.',
  case3_m1:'Drafts',
  case3_l1:'Генерируются',
  case3_m2:'Tone',
  case3_l2:'Единый стиль',
  case3_m3:'Calendar',
  case3_l3:'Планирование',
  case4_t:'Client intake для юристов или консалтинга',
  case4_d:'Формы собирают детали, классифицируют запрос, суммаризируют факты и готовят следующий шаг для команды.',
  case4_m1:'Forms',
  case4_l1:'Структура',
  case4_m2:'Docs',
  case4_l2:'Сводки',
  case4_m3:'Next step',
  case4_l3:'Подсказка',
  case5_t:'Guest support bot для hospitality',
  case5_d:'Мультиязычный ассистент отвечает на вопросы о брони, правилах, check-in и маршрутизирует срочные запросы.',
  case5_m1:'Guests',
  case5_l1:'Ответы',
  case5_m2:'Languages',
  case5_l2:'Поддержка',
  case5_m3:'Requests',
  case5_l3:'Routing',
  case6_t:'Candidate screening для рекрутинга',
  case6_d:'AI проверяет заявки по критериям, тегирует кандидатов, делает CV-сводки и помогает назначать интервью.',
  case6_m1:'CVs',
  case6_l1:'Скрининг',
  case6_m2:'Scores',
  case6_l2:'Оценки',
  case6_m3:'Interviews',
  case6_l3:'Планирование',
  cases_cta:'Обсудить workflow',

  about_kicker:'О Operix',
  about_h1:'Сфокусированная AI automation студия.',
  about_sub:'Operix строит практичные AI-системы для малого и среднего бизнеса, которому нужны результаты, а не хайп.',
  about_mission_k:'Миссия',
  about_mission_h:'AI-автоматизация должна быть доступной, полезной и честной.',
  about_mission_p1:'Мы помогаем бизнесу убрать повторяющуюся работу, отвечать быстрее и строить более чистые операции с AI.',
  about_mission_p2:'Мы выбираем маленькие измеримые системы вместо раздутого консалтинга. Сначала доказываем пользу, потом масштабируем то, что работает.',
  about_stat1:'Prototype-first',
  about_stat1_d:'Вы быстро видите рабочую систему.',
  about_stat2:'EN/RU',
  about_stat2_d:'Коммуникация и системы могут поддерживать оба языка.',
  about_stat3:'Remote',
  about_stat3_d:'Подходит для глобальных online-first команд.',
  about_why_k:'Принципы',
  about_why_h:'Как мы работаем.',
  about_v1_h:'Ясность',
  about_v1_p:'Вы понимаете, что мы строим, зачем это нужно и сколько стоит.',
  about_v2_h:'Скорость',
  about_v2_p:'Мы двигаемся быстро, но не выдаём недоделанное за готовое.',
  about_v3_h:'Честность',
  about_v3_p:'Без фейковых кейсов, завышенных обещаний и запутанного техно-языка.',
  about_v4_h:'Системное мышление',
  about_v4_p:'Мы не просто добавляем AI. Мы перестраиваем workflow вокруг полезной автоматизации.',
  about_v5_h:'Итерации',
  about_v5_p:'Хорошая автоматизация улучшается после контакта с реальными пользователями.',
  about_v6_h:'Ответственность',
  about_v6_p:'Мы документируем систему, чтобы команда понимала и использовала её.',

  blog_kicker:'Playbooks',
  blog_h1:'Заметки и гайды по AI-автоматизации.',
  blog_sub:'Без фейковых ссылок на блог. Это запланированные playbooks и темы, которые можно превратить в полноценные статьи.',
  blog_note:'Блог намеренно отмечен как coming soon, пока каждая статья реально не опубликована.',
  blog1_t:'Как автоматизировать поддержку за 5 дней',
  blog1_p:'Практичный план: FAQ, каналы, тестирование ответов и human handoff.',
  blog2_t:'Реальный ROI AI-автоматизации для малого бизнеса',
  blog2_p:'Как измерять сэкономленное время, скорость ответа, снижение затрат и рост конверсии без фейковых цифр.',
  blog3_t:'AI workflows для агентств недвижимости',
  blog3_p:'Квалификация лидов, запись на просмотры, CRM updates и follow-up цепочки.',
  blog4_t:'Telegram vs WhatsApp для business bots',
  blog4_p:'Какой канал подходит под аудиторию, бюджет, compliance и ежедневный workflow.',
  blog5_t:'Что автоматизировать в e-commerce первым',
  blog5_p:'Статус заказов, возвраты, abandoned carts, review requests и описания товаров.',
  blog6_t:'Как запускать multilingual support bot',
  blog6_p:'Определение языка, fallback-сообщения, escalation и тесты по регионам.',
  blog_status:'Скоро',

  contact_kicker:'Контакты',
  contact_h1:'Расскажите, что хотите автоматизировать.',
  contact_sub:'Отправьте workflow, инструменты и цель. Мы ответим с самой понятной первой точкой автоматизации.',
  contact_left_h:'Бесплатный аудит',
  contact_left_p:'Без давления и фейкового strategy call. Мы смотрим на процесс и говорим, что стоит автоматизировать первым.',
  contact_b1:'Разбор workflow',
  contact_b2:'Идея автоматизации',
  contact_b3:'Рекомендуемые tools',
  contact_b4:'Примерный бюджет',
  contact_b5:'Следующий шаг',
  contact_form_h:'Заявка на проект',
  contact_form_p:'Форма доставляется через Formspree на нашу почту.',
  contact_name:'Имя',
  contact_email:'Email',
  contact_company:'Компания',
  contact_budget:'Бюджет',
  contact_service:'Услуга',
  contact_message:'Сообщение',
  contact_send:'Отправить',
  contact_privacy:'Сообщение может быть обработано Formspree, чтобы доставить его в Operix. Мы не продаём ваши данные.',
  contact_success_h:'Сообщение отправлено.',
  contact_success_p:'Спасибо. Мы изучим workflow и ответим как можно скорее.',
  contact_error:'Ошибка. Напишите нам: travisofwork@gmail.com',

  privacy_kicker:'Legal',
  privacy_h1:'Политика конфиденциальности',
  privacy_sub:'Обновлено: июнь 2026',
  privacy_intro:'Operix уважает вашу приватность. Здесь объясняется, какие данные мы собираем и как используем.',
  privacy_h2_1:'Какие данные мы собираем',
  privacy_l1:'Данные из контактной формы: имя, email, компания, бюджет, выбранная услуга и сообщение.',
  privacy_l2:'Сообщения, которые вы отправляете нам через Telegram или email.',
  privacy_l3:'Базовые данные использования сайта, если подключена аналитика.',
  privacy_h2_2:'Как мы используем данные',
  privacy_l4:'Чтобы ответить на запрос и оказать услуги.',
  privacy_l5:'Чтобы подготовить предложение, scope проекта и общаться по delivery.',
  privacy_l6:'Чтобы улучшать сайт и услуги.',
  privacy_l7:'Мы не продаём ваши персональные данные.',
  privacy_h2_3:'Formspree',
  privacy_p3:'Контактная форма использует Formspree для доставки заявок на нашу почту. Поэтому данные формы могут обрабатываться Formspree как сторонним сервисом.',
  privacy_h2_4:'Хранение данных',
  privacy_p4:'Мы храним переписку только столько, сколько нужно для бизнеса, юридических целей и оказания услуг.',
  privacy_h2_5:'Ваши права',
  privacy_p5:'Вы можете запросить доступ, исправление или удаление персональных данных по email travisofwork@gmail.com.',
  privacy_h2_6:'Контакт',
  privacy_p6:'Вопросы по приватности: travisofwork@gmail.com или Telegram @exyysdof.',

  terms_kicker:'Legal',
  terms_h1:'Условия оказания услуг',
  terms_sub:'Обновлено: июнь 2026',
  terms_intro:'Работая с Operix, вы соглашаетесь с этими условиями. Детали конкретного проекта фиксируются в proposal или agreement.',
  terms_h2_1:'Услуги',
  terms_p1:'Operix предоставляет разработку AI-автоматизаций, проектирование workflow, настройку чатботов, интеграции и консалтинг.',
  terms_h2_2:'Scope',
  terms_p2:'У каждого проекта должен быть согласованный scope, deliverables, timeline и цена до начала работы.',
  terms_h2_3:'Оплата',
  terms_l1:'Обычно проекты оплачиваются 50% upfront и 50% после delivery, если не согласовано иначе.',
  terms_l2:'Ретейнеры оплачиваются ежемесячно заранее.',
  terms_l3:'Сторонние расходы: API, hosting или automation platforms — отдельно, если они не включены в proposal.',
  terms_h2_4:'Delivery',
  terms_p4:'Сроки являются оценкой. Задержки из-за отсутствия обратной связи, сторонних инструментов или изменения scope могут менять timeline.',
  terms_h2_5:'Правки',
  terms_p5:'Проекты включают разумные правки в рамках согласованного scope. Новые фичи или изменение scope могут потребовать доплаты.',
  terms_h2_6:'Возвраты',
  terms_p6:'Если Operix не выполняет согласованный scope, мы обсуждаем исправление или возврат. Возвраты не делаются при change-of-mind после старта работ.',
  terms_h2_7:'Ответственность',
  terms_p7:'Operix не отвечает за косвенные убытки. Максимальная ответственность ограничена суммой, оплаченной за конкретный проект.',
  terms_h2_8:'Контакт',
  terms_p8:'Вопросы: travisofwork@gmail.com или Telegram @exyysdof.'
};

function opxLang(){
  return localStorage.getItem('operix_lang') === 'ru' ? 'ru' : 'en';
}
function applyOpxPageCopy(){
  const l = opxLang();
  const copy = OPX_PAGE_COPY[l] || OPX_PAGE_COPY.en;
  document.documentElement.lang = l;
  document.querySelectorAll('[data-p]').forEach(el => {
    const key = el.getAttribute('data-p');
    if (copy[key] !== undefined) el.innerHTML = copy[key];
  });
  document.querySelectorAll('[data-ph]').forEach(el => {
    const key = el.getAttribute('data-ph');
    if (copy[key] !== undefined) el.setAttribute('placeholder', copy[key]);
  });
}
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', applyOpxPageCopy);
} else {
  applyOpxPageCopy();
}
document.addEventListener('click', e => {
  if (e.target.closest('.lang-btn')) {
    setTimeout(applyOpxPageCopy, 80);
    setTimeout(applyOpxPageCopy, 240);
  }
});
setTimeout(applyOpxPageCopy, 500);
